import { type NextPage } from "next";
import React from 'react';
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import AddCoffee from "../components/AddCoffee"
import CoffeeModal from "../components/CoffeeModal"
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  const coffeeList = trpc.coffee.getAll.useQuery();
  const coffeeMutation = trpc.coffee.create.useMutation()

  return (
    <>
      <Head>
        <title>Coffee-Mate</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-white">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-black sm:text-[5rem]">
            Coffee<span className="text-[hsl(15,42%,35%)]">Mate☕</span>
          </h1>
          <div>
            <AddCoffee coffeeMutation={coffeeMutation} />
          </div>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            {coffeeList?.data?.map((coffee, idx) => (
              <div key={idx}>
                <CoffeeModal data={coffee} />
              </div>
            ))}
          </div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-md text-black">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-black">
        {sessionData && <span>Welcome back <b>{sessionData.user?.name}</b></span>}
      </p>
      <p>
        {secretMessage && <span>{secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-black/10 px-10 py-3 font-semibold text-black no-underline transition hover:bg-pink-500"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out 👋" : "Sign in"}
      </button>
    </div>
  );
};
